// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ED
{
    
    
    [System.SerializableAttribute()]
    public class Item
    {
        
        // 编号
        public uint id;
        
        // 名字
        public string name;
        
        // 类型
        public uint type;
        
        // 攻击力
        public uint attack;
    }
}
