// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace ED
{
    
    
    [System.SerializableAttribute()]
    public class ItemConfig : ScriptableObject
    {
        
        // 数据集合
        public List<Item> ConfigInfoList;
        
        // 数据字典
        public Dictionary<System.UInt32,Item> ConfigInfoDic;
        
        public Item GetConfigByKey(uint key)
        {

            if (ConfigInfoList == null || ConfigInfoList.Count <= 0)
                return null;
            if(ConfigInfoDic==null)ConfigInfoDic = new Dictionary<System.UInt32,Item>();
            if(ConfigInfoDic.Count<=0)
                for(int i=0;i<ConfigInfoList.Count;i++)
                    ConfigInfoDic.Add(ConfigInfoList[i].id,ConfigInfoList[i]);
            Item target = null;
            ConfigInfoDic.TryGetValue( key, out target);
            return target;
        }
    }
}

